<?php


namespace Crud\Auto;


class LeftMenuPreferences
{


    public static function getLeftMenuSectionBlocks()
    {
        return [
    'Website' => [
        'prestashop16.ps_access',
        'prestashop16.ps_accessory',
        'prestashop16.ps_address',
        'prestashop16.ps_address_format',
        'prestashop16.ps_advice',
        'prestashop16.ps_advice_lang',
        'prestashop16.ps_alias',
        'prestashop16.ps_attachment',
        'prestashop16.ps_attachment_lang',
        'prestashop16.ps_attribute',
        'prestashop16.ps_attribute_group',
        'prestashop16.ps_attribute_group_lang',
        'prestashop16.ps_attribute_group_shop',
        'prestashop16.ps_attribute_impact',
        'prestashop16.ps_attribute_lang',
        'prestashop16.ps_attribute_shop',
        'prestashop16.ps_badge',
        'prestashop16.ps_badge_lang',
        'prestashop16.ps_belvg_CA_customerattributes',
        'prestashop16.ps_belvg_CA_customerattributes_customer',
        'prestashop16.ps_belvg_CA_customerattributes_lang',
        'prestashop16.ps_belvg_CA_customerattributes_shop',
        'prestashop16.ps_carrier',
        'prestashop16.ps_carrier_group',
        'prestashop16.ps_carrier_lang',
        'prestashop16.ps_carrier_shop',
        'prestashop16.ps_carrier_tax_rules_group_shop',
        'prestashop16.ps_carrier_zone',
        'prestashop16.ps_cart',
        'prestashop16.ps_cart_cart_rule',
        'prestashop16.ps_cart_product',
        'prestashop16.ps_cart_rule',
        'prestashop16.ps_cart_rule_carrier',
        'prestashop16.ps_cart_rule_combination',
        'prestashop16.ps_cart_rule_country',
        'prestashop16.ps_cart_rule_group',
        'prestashop16.ps_cart_rule_lang',
        'prestashop16.ps_cart_rule_product_rule',
        'prestashop16.ps_cart_rule_product_rule_group',
        'prestashop16.ps_cart_rule_product_rule_value',
        'prestashop16.ps_cart_rule_shop',
        'prestashop16.ps_category',
        'prestashop16.ps_category_group',
        'prestashop16.ps_category_lang',
        'prestashop16.ps_category_product',
        'prestashop16.ps_category_shop',
        'prestashop16.ps_cms',
        'prestashop16.ps_cms_block',
        'prestashop16.ps_cms_block_lang',
        'prestashop16.ps_cms_block_page',
        'prestashop16.ps_cms_block_shop',
        'prestashop16.ps_cms_category',
        'prestashop16.ps_cms_category_lang',
        'prestashop16.ps_cms_category_shop',
        'prestashop16.ps_cms_lang',
        'prestashop16.ps_cms_role',
        'prestashop16.ps_cms_role_lang',
        'prestashop16.ps_cms_shop',
        'prestashop16.ps_compare',
        'prestashop16.ps_compare_product',
        'prestashop16.ps_condition',
        'prestashop16.ps_condition_advice',
        'prestashop16.ps_condition_badge',
        'prestashop16.ps_configuration',
        'prestashop16.ps_configuration_kpi',
        'prestashop16.ps_configuration_kpi_lang',
        'prestashop16.ps_configuration_lang',
        'prestashop16.ps_connections',
        'prestashop16.ps_connections_page',
        'prestashop16.ps_connections_source',
        'prestashop16.ps_contact',
        'prestashop16.ps_contact_lang',
        'prestashop16.ps_contact_shop',
        'prestashop16.ps_country',
        'prestashop16.ps_country_lang',
        'prestashop16.ps_country_shop',
        'prestashop16.ps_cronjobs',
        'prestashop16.ps_currency',
        'prestashop16.ps_currency_shop',
        'prestashop16.ps_customer',
        'prestashop16.ps_customer_group',
        'prestashop16.ps_customer_message',
        'prestashop16.ps_customer_message_sync_imap',
        'prestashop16.ps_customer_thread',
        'prestashop16.ps_customer_vatncg',
        'prestashop16.ps_customization',
        'prestashop16.ps_customization_field',
        'prestashop16.ps_customization_field_lang',
        'prestashop16.ps_customized_data',
        'prestashop16.ps_date_range',
        'prestashop16.ps_delivery',
        'prestashop16.ps_employee',
        'prestashop16.ps_employee_shop',
        'prestashop16.ps_feature',
        'prestashop16.ps_feature_lang',
        'prestashop16.ps_feature_product',
        'prestashop16.ps_feature_shop',
        'prestashop16.ps_feature_value',
        'prestashop16.ps_feature_value_lang',
        'prestashop16.ps_gender',
        'prestashop16.ps_gender_lang',
        'prestashop16.ps_group',
        'prestashop16.ps_group_lang',
        'prestashop16.ps_group_reduction',
        'prestashop16.ps_group_shop',
        'prestashop16.ps_guest',
        'prestashop16.ps_homeslider',
        'prestashop16.ps_homeslider_slides',
        'prestashop16.ps_homeslider_slides_lang',
        'prestashop16.ps_hook',
        'prestashop16.ps_hook_alias',
        'prestashop16.ps_hook_module',
        'prestashop16.ps_hook_module_exceptions',
        'prestashop16.ps_image',
        'prestashop16.ps_image_lang',
        'prestashop16.ps_image_shop',
        'prestashop16.ps_image_type',
        'prestashop16.ps_import_match',
        'prestashop16.ps_info',
        'prestashop16.ps_info_lang',
        'prestashop16.ps_lang',
        'prestashop16.ps_lang_shop',
        'prestashop16.ps_layered_category',
        'prestashop16.ps_layered_filter',
        'prestashop16.ps_layered_filter_shop',
        'prestashop16.ps_layered_friendly_url',
        'prestashop16.ps_layered_indexable_attribute_group',
        'prestashop16.ps_layered_indexable_attribute_group_lang_value',
        'prestashop16.ps_layered_indexable_attribute_lang_value',
        'prestashop16.ps_layered_indexable_feature',
        'prestashop16.ps_layered_indexable_feature_lang_value',
        'prestashop16.ps_layered_indexable_feature_value_lang_value',
        'prestashop16.ps_layered_price_index',
        'prestashop16.ps_layered_product_attribute',
        'prestashop16.ps_linksmenutop',
        'prestashop16.ps_linksmenutop_lang',
        'prestashop16.ps_log',
        'prestashop16.ps_mail',
        'prestashop16.ps_manufacturer',
        'prestashop16.ps_manufacturer_lang',
        'prestashop16.ps_manufacturer_shop',
        'prestashop16.ps_memcached_servers',
        'prestashop16.ps_message',
        'prestashop16.ps_message_readed',
        'prestashop16.ps_meta',
        'prestashop16.ps_meta_lang',
        'prestashop16.ps_module',
        'prestashop16.ps_module_access',
        'prestashop16.ps_module_country',
        'prestashop16.ps_module_currency',
        'prestashop16.ps_module_group',
        'prestashop16.ps_module_preference',
        'prestashop16.ps_module_shop',
        'prestashop16.ps_modules_perfs',
        'prestashop16.ps_newsletter',
        'prestashop16.ps_operating_system',
        'prestashop16.ps_order_carrier',
        'prestashop16.ps_order_cart_rule',
        'prestashop16.ps_order_detail',
        'prestashop16.ps_order_detail_tax',
        'prestashop16.ps_order_history',
        'prestashop16.ps_order_invoice',
        'prestashop16.ps_order_invoice_payment',
        'prestashop16.ps_order_invoice_tax',
        'prestashop16.ps_order_message',
        'prestashop16.ps_order_message_lang',
        'prestashop16.ps_order_payment',
        'prestashop16.ps_order_return',
        'prestashop16.ps_order_return_detail',
        'prestashop16.ps_order_return_state',
        'prestashop16.ps_order_return_state_lang',
        'prestashop16.ps_order_slip',
        'prestashop16.ps_order_slip_detail',
        'prestashop16.ps_order_slip_detail_tax',
        'prestashop16.ps_order_state',
        'prestashop16.ps_order_state_lang',
        'prestashop16.ps_orders',
        'prestashop16.ps_pack',
        'prestashop16.ps_page',
        'prestashop16.ps_page_type',
        'prestashop16.ps_page_viewed',
        'prestashop16.ps_pagenotfound',
        'prestashop16.ps_product',
        'prestashop16.ps_product_attachment',
        'prestashop16.ps_product_attribute',
        'prestashop16.ps_product_attribute_combination',
        'prestashop16.ps_product_attribute_image',
        'prestashop16.ps_product_attribute_shop',
        'prestashop16.ps_product_carrier',
        'prestashop16.ps_product_country_tax',
        'prestashop16.ps_product_download',
        'prestashop16.ps_product_group_reduction_cache',
        'prestashop16.ps_product_lang',
        'prestashop16.ps_product_sale',
        'prestashop16.ps_product_shop',
        'prestashop16.ps_product_supplier',
        'prestashop16.ps_product_tag',
        'prestashop16.ps_profile',
        'prestashop16.ps_profile_lang',
        'prestashop16.ps_quick_access',
        'prestashop16.ps_quick_access_lang',
        'prestashop16.ps_range_price',
        'prestashop16.ps_range_weight',
        'prestashop16.ps_referrer',
        'prestashop16.ps_referrer_cache',
        'prestashop16.ps_referrer_shop',
        'prestashop16.ps_request_sql',
        'prestashop16.ps_required_field',
        'prestashop16.ps_risk',
        'prestashop16.ps_risk_lang',
        'prestashop16.ps_scene',
        'prestashop16.ps_scene_category',
        'prestashop16.ps_scene_lang',
        'prestashop16.ps_scene_products',
        'prestashop16.ps_scene_shop',
        'prestashop16.ps_search_engine',
        'prestashop16.ps_search_index',
        'prestashop16.ps_search_word',
        'prestashop16.ps_sekeyword',
        'prestashop16.ps_shop',
        'prestashop16.ps_shop_group',
        'prestashop16.ps_shop_url',
        'prestashop16.ps_smarty_cache',
        'prestashop16.ps_smarty_last_flush',
        'prestashop16.ps_smarty_lazy_cache',
        'prestashop16.ps_specific_price',
        'prestashop16.ps_specific_price_priority',
        'prestashop16.ps_specific_price_rule',
        'prestashop16.ps_specific_price_rule_condition',
        'prestashop16.ps_specific_price_rule_condition_group',
        'prestashop16.ps_state',
        'prestashop16.ps_statssearch',
        'prestashop16.ps_stock',
        'prestashop16.ps_stock_available',
        'prestashop16.ps_stock_mvt',
        'prestashop16.ps_stock_mvt_reason',
        'prestashop16.ps_stock_mvt_reason_lang',
        'prestashop16.ps_store',
        'prestashop16.ps_store_shop',
        'prestashop16.ps_supplier',
        'prestashop16.ps_supplier_lang',
        'prestashop16.ps_supplier_shop',
        'prestashop16.ps_supply_order',
        'prestashop16.ps_supply_order_detail',
        'prestashop16.ps_supply_order_history',
        'prestashop16.ps_supply_order_receipt_history',
        'prestashop16.ps_supply_order_state',
        'prestashop16.ps_supply_order_state_lang',
        'prestashop16.ps_tab',
        'prestashop16.ps_tab_advice',
        'prestashop16.ps_tab_lang',
        'prestashop16.ps_tab_module_preference',
        'prestashop16.ps_tag',
        'prestashop16.ps_tag_count',
        'prestashop16.ps_tax',
        'prestashop16.ps_tax_lang',
        'prestashop16.ps_tax_rule',
        'prestashop16.ps_tax_rules_group',
        'prestashop16.ps_tax_rules_group_shop',
        'prestashop16.ps_theme',
        'prestashop16.ps_theme_meta',
        'prestashop16.ps_theme_specific',
        'prestashop16.ps_themeconfigurator',
        'prestashop16.ps_timezone',
        'prestashop16.ps_warehouse',
        'prestashop16.ps_warehouse_carrier',
        'prestashop16.ps_warehouse_product_location',
        'prestashop16.ps_warehouse_shop',
        'prestashop16.ps_web_browser',
        'prestashop16.ps_webservice_account',
        'prestashop16.ps_webservice_account_shop',
        'prestashop16.ps_webservice_permission',
        'prestashop16.ps_zone',
        'prestashop16.ps_zone_shop',
    ],
];
    }

    /**
     * Labels are used in the left menu only
     */
    public static function getTableLabels()
    {
        return [
    'prestashop16.ps_access' => 'ps access',
    'prestashop16.ps_accessory' => 'ps accessory',
    'prestashop16.ps_address' => 'ps address',
    'prestashop16.ps_address_format' => 'ps address format',
    'prestashop16.ps_advice' => 'ps advice',
    'prestashop16.ps_advice_lang' => 'ps advice lang',
    'prestashop16.ps_alias' => 'ps alias',
    'prestashop16.ps_attachment' => 'ps attachment',
    'prestashop16.ps_attachment_lang' => 'ps attachment lang',
    'prestashop16.ps_attribute' => 'ps attribute',
    'prestashop16.ps_attribute_group' => 'ps attribute group',
    'prestashop16.ps_attribute_group_lang' => 'ps attribute group lang',
    'prestashop16.ps_attribute_group_shop' => 'ps attribute group shop',
    'prestashop16.ps_attribute_impact' => 'ps attribute impact',
    'prestashop16.ps_attribute_lang' => 'ps attribute lang',
    'prestashop16.ps_attribute_shop' => 'ps attribute shop',
    'prestashop16.ps_badge' => 'ps badge',
    'prestashop16.ps_badge_lang' => 'ps badge lang',
    'prestashop16.ps_belvg_CA_customerattributes' => 'ps belvg CA customerattributes',
    'prestashop16.ps_belvg_CA_customerattributes_customer' => 'ps belvg CA customerattributes customer',
    'prestashop16.ps_belvg_CA_customerattributes_lang' => 'ps belvg CA customerattributes lang',
    'prestashop16.ps_belvg_CA_customerattributes_shop' => 'ps belvg CA customerattributes shop',
    'prestashop16.ps_carrier' => 'ps carrier',
    'prestashop16.ps_carrier_group' => 'ps carrier group',
    'prestashop16.ps_carrier_lang' => 'ps carrier lang',
    'prestashop16.ps_carrier_shop' => 'ps carrier shop',
    'prestashop16.ps_carrier_tax_rules_group_shop' => 'ps carrier tax rules group shop',
    'prestashop16.ps_carrier_zone' => 'ps carrier zone',
    'prestashop16.ps_cart' => 'ps cart',
    'prestashop16.ps_cart_cart_rule' => 'ps cart cart rule',
    'prestashop16.ps_cart_product' => 'ps cart product',
    'prestashop16.ps_cart_rule' => 'ps cart rule',
    'prestashop16.ps_cart_rule_carrier' => 'ps cart rule carrier',
    'prestashop16.ps_cart_rule_combination' => 'ps cart rule combination',
    'prestashop16.ps_cart_rule_country' => 'ps cart rule country',
    'prestashop16.ps_cart_rule_group' => 'ps cart rule group',
    'prestashop16.ps_cart_rule_lang' => 'ps cart rule lang',
    'prestashop16.ps_cart_rule_product_rule' => 'ps cart rule product rule',
    'prestashop16.ps_cart_rule_product_rule_group' => 'ps cart rule product rule group',
    'prestashop16.ps_cart_rule_product_rule_value' => 'ps cart rule product rule value',
    'prestashop16.ps_cart_rule_shop' => 'ps cart rule shop',
    'prestashop16.ps_category' => 'ps category',
    'prestashop16.ps_category_group' => 'ps category group',
    'prestashop16.ps_category_lang' => 'ps category lang',
    'prestashop16.ps_category_product' => 'ps category product',
    'prestashop16.ps_category_shop' => 'ps category shop',
    'prestashop16.ps_cms' => 'ps cms',
    'prestashop16.ps_cms_block' => 'ps cms block',
    'prestashop16.ps_cms_block_lang' => 'ps cms block lang',
    'prestashop16.ps_cms_block_page' => 'ps cms block page',
    'prestashop16.ps_cms_block_shop' => 'ps cms block shop',
    'prestashop16.ps_cms_category' => 'ps cms category',
    'prestashop16.ps_cms_category_lang' => 'ps cms category lang',
    'prestashop16.ps_cms_category_shop' => 'ps cms category shop',
    'prestashop16.ps_cms_lang' => 'ps cms lang',
    'prestashop16.ps_cms_role' => 'ps cms role',
    'prestashop16.ps_cms_role_lang' => 'ps cms role lang',
    'prestashop16.ps_cms_shop' => 'ps cms shop',
    'prestashop16.ps_compare' => 'ps compare',
    'prestashop16.ps_compare_product' => 'ps compare product',
    'prestashop16.ps_condition' => 'ps condition',
    'prestashop16.ps_condition_advice' => 'ps condition advice',
    'prestashop16.ps_condition_badge' => 'ps condition badge',
    'prestashop16.ps_configuration' => 'ps configuration',
    'prestashop16.ps_configuration_kpi' => 'ps configuration kpi',
    'prestashop16.ps_configuration_kpi_lang' => 'ps configuration kpi lang',
    'prestashop16.ps_configuration_lang' => 'ps configuration lang',
    'prestashop16.ps_connections' => 'ps connections',
    'prestashop16.ps_connections_page' => 'ps connections page',
    'prestashop16.ps_connections_source' => 'ps connections source',
    'prestashop16.ps_contact' => 'ps contact',
    'prestashop16.ps_contact_lang' => 'ps contact lang',
    'prestashop16.ps_contact_shop' => 'ps contact shop',
    'prestashop16.ps_country' => 'ps country',
    'prestashop16.ps_country_lang' => 'ps country lang',
    'prestashop16.ps_country_shop' => 'ps country shop',
    'prestashop16.ps_cronjobs' => 'ps cronjobs',
    'prestashop16.ps_currency' => 'ps currency',
    'prestashop16.ps_currency_shop' => 'ps currency shop',
    'prestashop16.ps_customer' => 'ps customer',
    'prestashop16.ps_customer_group' => 'ps customer group',
    'prestashop16.ps_customer_message' => 'ps customer message',
    'prestashop16.ps_customer_message_sync_imap' => 'ps customer message sync imap',
    'prestashop16.ps_customer_thread' => 'ps customer thread',
    'prestashop16.ps_customer_vatncg' => 'ps customer vatncg',
    'prestashop16.ps_customization' => 'ps customization',
    'prestashop16.ps_customization_field' => 'ps customization field',
    'prestashop16.ps_customization_field_lang' => 'ps customization field lang',
    'prestashop16.ps_customized_data' => 'ps customized data',
    'prestashop16.ps_date_range' => 'ps date range',
    'prestashop16.ps_delivery' => 'ps delivery',
    'prestashop16.ps_employee' => 'ps employee',
    'prestashop16.ps_employee_shop' => 'ps employee shop',
    'prestashop16.ps_feature' => 'ps feature',
    'prestashop16.ps_feature_lang' => 'ps feature lang',
    'prestashop16.ps_feature_product' => 'ps feature product',
    'prestashop16.ps_feature_shop' => 'ps feature shop',
    'prestashop16.ps_feature_value' => 'ps feature value',
    'prestashop16.ps_feature_value_lang' => 'ps feature value lang',
    'prestashop16.ps_gender' => 'ps gender',
    'prestashop16.ps_gender_lang' => 'ps gender lang',
    'prestashop16.ps_group' => 'ps group',
    'prestashop16.ps_group_lang' => 'ps group lang',
    'prestashop16.ps_group_reduction' => 'ps group reduction',
    'prestashop16.ps_group_shop' => 'ps group shop',
    'prestashop16.ps_guest' => 'ps guest',
    'prestashop16.ps_homeslider' => 'ps homeslider',
    'prestashop16.ps_homeslider_slides' => 'ps homeslider slides',
    'prestashop16.ps_homeslider_slides_lang' => 'ps homeslider slides lang',
    'prestashop16.ps_hook' => 'ps hook',
    'prestashop16.ps_hook_alias' => 'ps hook alias',
    'prestashop16.ps_hook_module' => 'ps hook module',
    'prestashop16.ps_hook_module_exceptions' => 'ps hook module exceptions',
    'prestashop16.ps_image' => 'ps image',
    'prestashop16.ps_image_lang' => 'ps image lang',
    'prestashop16.ps_image_shop' => 'ps image shop',
    'prestashop16.ps_image_type' => 'ps image type',
    'prestashop16.ps_import_match' => 'ps import match',
    'prestashop16.ps_info' => 'ps info',
    'prestashop16.ps_info_lang' => 'ps info lang',
    'prestashop16.ps_lang' => 'ps lang',
    'prestashop16.ps_lang_shop' => 'ps lang shop',
    'prestashop16.ps_layered_category' => 'ps layered category',
    'prestashop16.ps_layered_filter' => 'ps layered filter',
    'prestashop16.ps_layered_filter_shop' => 'ps layered filter shop',
    'prestashop16.ps_layered_friendly_url' => 'ps layered friendly url',
    'prestashop16.ps_layered_indexable_attribute_group' => 'ps layered indexable attribute group',
    'prestashop16.ps_layered_indexable_attribute_group_lang_value' => 'ps layered indexable attribute group lang value',
    'prestashop16.ps_layered_indexable_attribute_lang_value' => 'ps layered indexable attribute lang value',
    'prestashop16.ps_layered_indexable_feature' => 'ps layered indexable feature',
    'prestashop16.ps_layered_indexable_feature_lang_value' => 'ps layered indexable feature lang value',
    'prestashop16.ps_layered_indexable_feature_value_lang_value' => 'ps layered indexable feature value lang value',
    'prestashop16.ps_layered_price_index' => 'ps layered price index',
    'prestashop16.ps_layered_product_attribute' => 'ps layered product attribute',
    'prestashop16.ps_linksmenutop' => 'ps linksmenutop',
    'prestashop16.ps_linksmenutop_lang' => 'ps linksmenutop lang',
    'prestashop16.ps_log' => 'ps log',
    'prestashop16.ps_mail' => 'ps mail',
    'prestashop16.ps_manufacturer' => 'ps manufacturer',
    'prestashop16.ps_manufacturer_lang' => 'ps manufacturer lang',
    'prestashop16.ps_manufacturer_shop' => 'ps manufacturer shop',
    'prestashop16.ps_memcached_servers' => 'ps memcached servers',
    'prestashop16.ps_message' => 'ps message',
    'prestashop16.ps_message_readed' => 'ps message readed',
    'prestashop16.ps_meta' => 'ps meta',
    'prestashop16.ps_meta_lang' => 'ps meta lang',
    'prestashop16.ps_module' => 'ps module',
    'prestashop16.ps_module_access' => 'ps module access',
    'prestashop16.ps_module_country' => 'ps module country',
    'prestashop16.ps_module_currency' => 'ps module currency',
    'prestashop16.ps_module_group' => 'ps module group',
    'prestashop16.ps_module_preference' => 'ps module preference',
    'prestashop16.ps_module_shop' => 'ps module shop',
    'prestashop16.ps_modules_perfs' => 'ps modules perfs',
    'prestashop16.ps_newsletter' => 'ps newsletter',
    'prestashop16.ps_operating_system' => 'ps operating system',
    'prestashop16.ps_order_carrier' => 'ps order carrier',
    'prestashop16.ps_order_cart_rule' => 'ps order cart rule',
    'prestashop16.ps_order_detail' => 'ps order detail',
    'prestashop16.ps_order_detail_tax' => 'ps order detail tax',
    'prestashop16.ps_order_history' => 'ps order history',
    'prestashop16.ps_order_invoice' => 'ps order invoice',
    'prestashop16.ps_order_invoice_payment' => 'ps order invoice payment',
    'prestashop16.ps_order_invoice_tax' => 'ps order invoice tax',
    'prestashop16.ps_order_message' => 'ps order message',
    'prestashop16.ps_order_message_lang' => 'ps order message lang',
    'prestashop16.ps_order_payment' => 'ps order payment',
    'prestashop16.ps_order_return' => 'ps order return',
    'prestashop16.ps_order_return_detail' => 'ps order return detail',
    'prestashop16.ps_order_return_state' => 'ps order return state',
    'prestashop16.ps_order_return_state_lang' => 'ps order return state lang',
    'prestashop16.ps_order_slip' => 'ps order slip',
    'prestashop16.ps_order_slip_detail' => 'ps order slip detail',
    'prestashop16.ps_order_slip_detail_tax' => 'ps order slip detail tax',
    'prestashop16.ps_order_state' => 'ps order state',
    'prestashop16.ps_order_state_lang' => 'ps order state lang',
    'prestashop16.ps_orders' => 'ps orders',
    'prestashop16.ps_pack' => 'ps pack',
    'prestashop16.ps_page' => 'ps page',
    'prestashop16.ps_page_type' => 'ps page type',
    'prestashop16.ps_page_viewed' => 'ps page viewed',
    'prestashop16.ps_pagenotfound' => 'ps pagenotfound',
    'prestashop16.ps_product' => 'ps product',
    'prestashop16.ps_product_attachment' => 'ps product attachment',
    'prestashop16.ps_product_attribute' => 'ps product attribute',
    'prestashop16.ps_product_attribute_combination' => 'ps product attribute combination',
    'prestashop16.ps_product_attribute_image' => 'ps product attribute image',
    'prestashop16.ps_product_attribute_shop' => 'ps product attribute shop',
    'prestashop16.ps_product_carrier' => 'ps product carrier',
    'prestashop16.ps_product_country_tax' => 'ps product country tax',
    'prestashop16.ps_product_download' => 'ps product download',
    'prestashop16.ps_product_group_reduction_cache' => 'ps product group reduction cache',
    'prestashop16.ps_product_lang' => 'ps product lang',
    'prestashop16.ps_product_sale' => 'ps product sale',
    'prestashop16.ps_product_shop' => 'ps product shop',
    'prestashop16.ps_product_supplier' => 'ps product supplier',
    'prestashop16.ps_product_tag' => 'ps product tag',
    'prestashop16.ps_profile' => 'ps profile',
    'prestashop16.ps_profile_lang' => 'ps profile lang',
    'prestashop16.ps_quick_access' => 'ps quick access',
    'prestashop16.ps_quick_access_lang' => 'ps quick access lang',
    'prestashop16.ps_range_price' => 'ps range price',
    'prestashop16.ps_range_weight' => 'ps range weight',
    'prestashop16.ps_referrer' => 'ps referrer',
    'prestashop16.ps_referrer_cache' => 'ps referrer cache',
    'prestashop16.ps_referrer_shop' => 'ps referrer shop',
    'prestashop16.ps_request_sql' => 'ps request sql',
    'prestashop16.ps_required_field' => 'ps required field',
    'prestashop16.ps_risk' => 'ps risk',
    'prestashop16.ps_risk_lang' => 'ps risk lang',
    'prestashop16.ps_scene' => 'ps scene',
    'prestashop16.ps_scene_category' => 'ps scene category',
    'prestashop16.ps_scene_lang' => 'ps scene lang',
    'prestashop16.ps_scene_products' => 'ps scene products',
    'prestashop16.ps_scene_shop' => 'ps scene shop',
    'prestashop16.ps_search_engine' => 'ps search engine',
    'prestashop16.ps_search_index' => 'ps search index',
    'prestashop16.ps_search_word' => 'ps search word',
    'prestashop16.ps_sekeyword' => 'ps sekeyword',
    'prestashop16.ps_shop' => 'ps shop',
    'prestashop16.ps_shop_group' => 'ps shop group',
    'prestashop16.ps_shop_url' => 'ps shop url',
    'prestashop16.ps_smarty_cache' => 'ps smarty cache',
    'prestashop16.ps_smarty_last_flush' => 'ps smarty last flush',
    'prestashop16.ps_smarty_lazy_cache' => 'ps smarty lazy cache',
    'prestashop16.ps_specific_price' => 'ps specific price',
    'prestashop16.ps_specific_price_priority' => 'ps specific price priority',
    'prestashop16.ps_specific_price_rule' => 'ps specific price rule',
    'prestashop16.ps_specific_price_rule_condition' => 'ps specific price rule condition',
    'prestashop16.ps_specific_price_rule_condition_group' => 'ps specific price rule condition group',
    'prestashop16.ps_state' => 'ps state',
    'prestashop16.ps_statssearch' => 'ps statssearch',
    'prestashop16.ps_stock' => 'ps stock',
    'prestashop16.ps_stock_available' => 'ps stock available',
    'prestashop16.ps_stock_mvt' => 'ps stock mvt',
    'prestashop16.ps_stock_mvt_reason' => 'ps stock mvt reason',
    'prestashop16.ps_stock_mvt_reason_lang' => 'ps stock mvt reason lang',
    'prestashop16.ps_store' => 'ps store',
    'prestashop16.ps_store_shop' => 'ps store shop',
    'prestashop16.ps_supplier' => 'ps supplier',
    'prestashop16.ps_supplier_lang' => 'ps supplier lang',
    'prestashop16.ps_supplier_shop' => 'ps supplier shop',
    'prestashop16.ps_supply_order' => 'ps supply order',
    'prestashop16.ps_supply_order_detail' => 'ps supply order detail',
    'prestashop16.ps_supply_order_history' => 'ps supply order history',
    'prestashop16.ps_supply_order_receipt_history' => 'ps supply order receipt history',
    'prestashop16.ps_supply_order_state' => 'ps supply order state',
    'prestashop16.ps_supply_order_state_lang' => 'ps supply order state lang',
    'prestashop16.ps_tab' => 'ps tab',
    'prestashop16.ps_tab_advice' => 'ps tab advice',
    'prestashop16.ps_tab_lang' => 'ps tab lang',
    'prestashop16.ps_tab_module_preference' => 'ps tab module preference',
    'prestashop16.ps_tag' => 'ps tag',
    'prestashop16.ps_tag_count' => 'ps tag count',
    'prestashop16.ps_tax' => 'ps tax',
    'prestashop16.ps_tax_lang' => 'ps tax lang',
    'prestashop16.ps_tax_rule' => 'ps tax rule',
    'prestashop16.ps_tax_rules_group' => 'ps tax rules group',
    'prestashop16.ps_tax_rules_group_shop' => 'ps tax rules group shop',
    'prestashop16.ps_theme' => 'ps theme',
    'prestashop16.ps_theme_meta' => 'ps theme meta',
    'prestashop16.ps_theme_specific' => 'ps theme specific',
    'prestashop16.ps_themeconfigurator' => 'ps themeconfigurator',
    'prestashop16.ps_timezone' => 'ps timezone',
    'prestashop16.ps_warehouse' => 'ps warehouse',
    'prestashop16.ps_warehouse_carrier' => 'ps warehouse carrier',
    'prestashop16.ps_warehouse_product_location' => 'ps warehouse product location',
    'prestashop16.ps_warehouse_shop' => 'ps warehouse shop',
    'prestashop16.ps_web_browser' => 'ps web browser',
    'prestashop16.ps_webservice_account' => 'ps webservice account',
    'prestashop16.ps_webservice_account_shop' => 'ps webservice account shop',
    'prestashop16.ps_webservice_permission' => 'ps webservice permission',
    'prestashop16.ps_zone' => 'ps zone',
    'prestashop16.ps_zone_shop' => 'ps zone shop',
];
    }

}