<?php
$prefs = [
    'actionColumnsPosition' => 'right',
    'prettyTableNames' => [
        'zilu.commande_has_article' => 'commande has article',
        'zilu.commande_ligne_statut' => 'commande ligne statut',
        'zilu.fournisseur_has_article' => 'fournisseur has article',
        'zilu.type_container' => 'type container',
    ],
    'foreignKeyPrettierColumns' => [
        'zilu.article' => 'reference_lf',
        'zilu.commande' => 'reference',
        'zilu.commande_ligne_statut' => 'nom',
        'zilu.container' => 'nom',
        'zilu.fournisseur' => 'nom',
        'zilu.sav' => 'fournisseur',
        'zilu.type_container' => 'label',
    ],
    'prettyColumnNames' => [
        'reference_lf' => 'reference lf',
        'reference_hldp' => 'reference hldp',
        'descr_fr' => 'descr fr',
        'descr_en' => 'descr en',
        'estimated_date' => 'estimated date',
        'commande_id' => 'commande',
        'article_id' => 'article',
        'container_id' => 'container',
        'fournisseur_id' => 'fournisseur',
        'sav_id' => 'sav',
        'commande_ligne_statut_id' => 'commande ligne statut',
        'prix_override' => 'prix override',
        'date_estimee' => 'date estimee',
        'type_container_id' => 'type container',
        'livre_le' => 'livre le',
        'nb_produits_defec' => 'nb produits defec',
        'date_notif' => 'date notif',
        'demande_remboursement' => 'demande remboursement',
        'montant_rembourse' => 'montant rembourse',
        'pourcentage_rembourse' => 'pourcentage rembourse',
        'date_remboursement' => 'date remboursement',
        'poids_max' => 'poids max',
        'volume_max' => 'volume max',
    ],
    'urlTransformerIf' => function ($c) {
            return (false !== strpos($c, 'url_'));
        },
];
