<?php


namespace CommandeLigneStatut;

class CommandeLigneStatut
{
    const STATUT_UN_PAS_ENCORE_TRAITE = 1;
    const STATUT_DEUX_ENVOYE_PAR_MAIL_A_DIDIER = 2;
    const STATUT_TROIS_ENVOYE_PAR_MAIL_AUX_FOURNISSEURS = 3;
    const STATUT_QUATRE_PROFORMAT_INVOICE_CONFIRME_AVEC_SIGNATURE = 4;
    const STATUT_CINQ_TRENTE_POURCENT_PAYE_PAR_LEADERFIT = 5;
    const STATUT_SIX_SOIXANTE_DIX_POURCENT_A_PAYER = 6;
    const STATUT_SEPT_FINI = 7;
}