<?php
$prefs = [
    'actionColumnsPosition' => 'right',
    'prettyTableNames' => [
        'oui.coups_de_coeur' => 'coups de coeur',
        'oui.equipe_has_membres' => 'equipe has membres',
        'oui.styles_musicaux' => 'styles musicaux',
        'oui.users_has_instruments' => 'users has instruments',
        'oui.users_has_styles_musicaux' => 'users has styles musicaux',
    ],
    'foreignKeyPrettierColumns' => [
        'oui.equipe' => 'nom',
        'oui.videos' => 'titre',
        'oui.membres' => 'pseudo',
        'oui.niveaux' => 'nom',
        'oui.pays' => 'nom',
        'oui.instruments' => 'nom',
        'oui.users' => 'email',
        'oui.styles_musicaux' => 'nom',
        'oui.concours' => 'titre',
    ],
    'prettyColumnNames' => [
        'equipe_id' => 'equipe',
        'url_photo' => 'url photo',
        'url_video' => 'url video',
        'date_debut' => 'date debut',
        'date_fin' => 'date fin',
        'videos_id' => 'videos',
        'membres_id' => 'membres',
        'date_creation' => 'date creation',
        'date_naissance' => 'date naissance',
        'code_postal' => 'code postal',
        'pays_id' => 'pays',
        'niveaux_id' => 'niveaux',
        'prochains_concerts' => 'prochains concerts',
        'sites_internet' => 'sites internet',
        'show_sexe' => 'show sexe',
        'show_date_naissance' => 'show date naissance',
        'show_niveau' => 'show niveau',
        'users_id' => 'users',
        'instruments_id' => 'instruments',
        'styles_musicaux_id' => 'styles musicaux',
        'concours_id' => 'concours',
        'nb_likes' => 'nb likes',
        'nb_vues' => 'nb vues',
    ],
    'urlTransformerIf' => function ($c) {
            return (false !== strpos($c, 'url_'));
        },
];
